In [1]:
import numpy as np
import dgl
import torch

In [2]:
filename = "/home/bear/workspace/single-gnn/data/raid/papers100M/feats.bin"
fpr = np.memmap(filename, dtype='float32', mode='r', shape=(111059956,128))
print(fpr)

[[-0.434013 -0.353623 -0.390505 ...  0.178895 -0.205813 -0.018228]
 [-0.255682  0.054082  0.10214  ... -0.138802 -0.266801 -0.233078]
 [-0.045137  0.202197 -0.010405 ...  0.07838  -0.079276 -0.147964]
 ...
 [-0.099699 -0.058251 -0.316907 ...  0.202848 -0.116325 -0.087191]
 [-0.093779 -0.122275 -0.022505 ...  0.168276  0.007435 -0.247139]
 [-0.123305  0.189822  0.007853 ...  0.347173 -0.050324 -0.153861]]
