In [2]:
from scipy.sparse import csr_matrix
from scipy.sparse import coo_matrix
import numpy as np 
import torch

In [7]:
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
t2 = torch.tensor([3, 5, 7])
indices = (t1[:, None] == t2).nonzero()[:, 0]
print(indices)

tensor([[0, 5],
        [2, 0],
        [4, 1],
        [6, 2]])


In [23]:
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
t2 = torch.tensor([3, 5, 7, 10,12,1])
indices = torch.full(t2.shape, -1, dtype=torch.long)
mask = (t1[:, None] == t2)
table = mask.nonzero().reshape(-1)
col_indices = table[::2]
row_indices = table[1::2]
indices[row_indices] = col_indices
non_negative_tensor = indices[indices >= 0]
print(non_negative_tensor)

tensor([2, 4, 6, 0])


In [20]:
row_indices

tensor([5, 0, 1, 2])

In [11]:
import torch

t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
t2 = torch.tensor([3, 5, 7, 10])

# 创建一个新的tensor来存储索引位置，初始值设置为-1
indices = torch.full(t2.shape, -1, dtype=torch.long)

# 使用torch.where函数找出t2中的元素在t1中的索引位置
for i, val in enumerate(t2):
    matching_indices = torch.where(t1 == val)
    if len(matching_indices[0]) > 0:
        indices[i] = matching_indices[0][0]

print(indices)


tensor([ 2,  4,  6, -1])
